### ISSUE TITLE
PIE.htc for border-radius and etc

### ISSUE THREAD

**Issue by evilebottnawi** [coliff/bootstrap-ie7#27]
What do you think?

**Comment by coliff** [comment]
Hi there. I gave this a mention in the FAQs on the ReadMe.md. I recommend CCS3Pie for adding support for those CSS3 properties to older IE. http://css3pie.com/. If you use that you can add this to your CSS to quickly add border-radius https://gist.github.com/coliff/5618329. I don't intend to include PIE.htc along with bootstrap-ie7, it's better for developers to have the choice whether to include it or not.

**Comment by sheo13666** [comment]
@coliff Maybe create a branch directly connected with CSS3Pie.
