### ISSUE TITLE
Bower version

### ISSUE THREAD

**Issue by jefferyto** [coliff/bootstrap-ie7#32]
Bower no longer reads the [version](https://github.com/bower/spec/blob/master/json.md#version) field in `bower.json`. Instead, it reads [semver tags](https://bower.io/docs/creating-packages/#register) from the repo. Would be great if a tag was added for the current version :smile:

**Comment by coliff** [comment]
Thanks for the heads-up. I just pushed the first release of this as v.3.3.7. I personally don't use Bower so please let me know if it works or not. Thanks again.
