### ISSUE TITLE
Working example page?

### ISSUE THREAD

**Issue by neilsmith** [coliff/bootstrap-ie7#4]
Hello,

This is a great idea, and I'd love to use it on a Bootstrap 3 site we're working on, help fix any issues we find, etc.

I realise it's a work-in-progress right now, but would you be expecting it to work yet on simple layouts? We're trying a straightforward layout with a few top sections, and a sidebar, and so far attempts to use boostrap-ie7 don't result in a working layout in IE7. (All the content just flows vertically.)

Is there a working example page somewhere that we can use as a template, and hopefully see where we're going wrong?

(If not, I'll see if I can extract our issues and make an example not-working-for-us page somewhere if you think that would be useful?)

Thanks,
Neil.

**Comment by coliff** [comment]
Closing this issue now since it's no longer needed.
